//COLOR//
#define COLOR_BLACK 0x0000
#define COLOR_WHITE 0xFFFF
#define COLOR_LIGHTGRAY 0xBDF7
#define COLOR_DARKGRAY 0x7BEF
#define COLOR_RED 0xF800
#define COLOR_YELLOW 0xFFE0
#define COLOR_ORANGE 0xFBE0
#define COLOR_BROWN 0x79E0
#define COLOR_GREEN 0x7E0
#define COLOR_CYAN 0x7FF
#define COLOR_BLUE 0x1F
#define COLOR_PINK 0xF81F
//#####//